"""added deal fields

Revision ID: 243d68fd85ff
Revises: 67a75d55c97f
Create Date: 2021-04-17 16:52:51.149708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243d68fd85ff'
down_revision = '67a75d55c97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('industry', sa.String(length=255), nullable=False))
    op.add_column('company', sa.Column('status', sa.String(length=255), nullable=False))
    op.add_column('deal_investor', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('deal_investor', sa.Column('fund_invested', sa.String(length=255), nullable=True))
    op.add_column('deal_investor', sa.Column('investment_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_investor', 'investment_type')
    op.drop_column('deal_investor', 'fund_invested')
    op.drop_column('deal_investor', 'date')
    op.drop_column('company', 'status')
    op.drop_column('company', 'industry')
    # ### end Alembic commands ###
