"""added highlights

Revision ID: 65b6bf89fa77
Revises: 243d68fd85ff
Create Date: 2021-04-17 18:43:14.834718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b6bf89fa77'
down_revision = '243d68fd85ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_highlight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_highlight')
    op.drop_table('highlight')
    # ### end Alembic commands ###
